---
version: "3.5"
services:
   jenkins-build:   
      build: docker-jenkins
      privileged: true
      ports:
       - 8080:8080
      user: root
      container_name: jenkins
      volumes:
       - /tmp/jenkins:/var/jenkins_home
       - /var/run/docker.sock:/var/run/docker.sock
   local-registry:
      image: docker.io/registry
      ports:
       - 5000:5000
...
